version: "3.1"
services:
  app:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
    - ./ritsoftv2:/var/www/html
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=ritsoftv2
      - MYSQL_PASSWORD=ritsoftv2
      - MYSQL_DB=ritsoftv2
#      - DEBUG_APP=true # Uncomment to enable error reporting
    networks:
      - default
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ritsoftv2
      MYSQL_USER: ritsoftv2
      MYSQL_PASSWORD: ritsoftv2
      MYSQL_ROOT_PASSWORD: ritsoftv2
    restart: always
    volumes:
      - ./ritsoft.sql:/docker-entrypoint-initdb.d/ritsoft.sql
      - ./docker/data:/var/lib/mysql
    networks:
      - default
networks:
  default: